bank_reviews_decisionnal:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: bank_reviews_decisionnal
      threads: 4
      keepalives_idle: 0

bank_reviews_transactional:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: bank_reviews_transactional
      threads: 4
      keepalives_idle: 0
